### ISSUE TITLE
Feature: Prometo anar en moto

### ISSUE THREAD

**Issue by Albert-Sanchez-UdG** [Albert-Sanchez-UdG/P2_Repo_Issue_PR#3]
M'agradaria anar en moto però m'estic fent gran i ja no és el mateix!!!
Algú em presta 20 anys de joventut?
Jajajaja!!!

**Comment by Albert-Sanchez-UdG** [comment]
Perfecte!!!

**Comment by FXGG-UdG** [comment]
T'has de comprar rejuvenil !!!
